<?php
/**
 * Octagono Ecommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 *
 *
 * @category   Cliente
 * @package    Octagono_Cliente
 * @copyright  Copyright (c) 2009-2011 - Octagono Ecommerce - www.octagonoecommerce.com.br
 * @license    http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 */
?>
<div class="field rgie">
	<label for="<?php echo $this->getFieldId('rgie')?>" class="required"><em>*</em><?php if($this->getTipo() == 2): ?><?php echo $this->__('IE') ?><?php else: ?><?php echo $this->__('RG') ?><?php endif ?></label>
	<div class="input-box">
	    <input type="text" id="<?php echo $this->getFieldId('rgie')?>" name="<?php echo $this->getFieldName('rgie')?>" value="<?php echo $this->escapeHtml($this->getRgie()) ?>" title="<?php if($this->getTipo() == 2): ?><?php echo $this->__('IE') ?><?php else: ?><?php echo $this->__('RG') ?><?php endif ?>" class="input-text required-entry" <?php echo $this->getFieldParams() ?> />
	</div>
</div>

