<?php
/**
 * Octagono Ecommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 *
 *
 * @category   Cliente
 * @package    Octagono_Cliente
 * @copyright  Copyright (c) 2009-2011 - Octagono Ecommerce - www.octagonoecommerce.com.br
 * @license    http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 */
?>
<div class="field profissao">
	<label for="<?php echo $this->getFieldId('profissao')?>"><?php echo $this->__('Profissão') ?></label>
	<div class="input-box">
	    <input type="text" id="<?php echo $this->getFieldId('profissao')?>" name="<?php echo $this->getFieldName('profissao')?>" value="<?php echo $this->escapeHtml($this->getProfissao()) ?>" title="<?php echo $this->__('Profissão') ?>" class="input-text" <?php echo $this->getFieldParams() ?> />
	</div>
</div>

