<?php
/**
 * Octagono Ecommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 *
 *
 * @category   Cliente
 * @package    Octagono_Cliente
 * @copyright  Copyright (c) 2009-2011 - Octagono Ecommerce - www.octagonoecommerce.com.br
 * @license    http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 */
?>
<div class="field taxvat">
	<label for="<?php echo $this->getFieldId('taxvat')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php if($this->getTipo() == 2): ?><?php echo $this->__('CNPJ') ?><?php else: ?><?php echo $this->__('CPF') ?><?php endif ?></label>
	<div class="input-box">
	    <input type="text" id="<?php echo $this->getFieldId('taxvat')?>" name="<?php echo $this->getFieldName('taxvat')?>" value="<?php echo $this->escapeHtml($this->getTaxvat()) ?>" title="<?php if($this->getTipo() == 2): ?><?php echo $this->__('CNPJ') ?><?php else: ?><?php echo $this->__('CPF') ?><?php endif ?>" class="input-text <?php if ($this->isRequired()):?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?> />
	</div>
</div>
<script type="text/javascript">
	//<![CDATA[
	$('<?php echo $this->getFieldId('taxvat'); ?>').addClassName('validar_cpf');
	Validation.add('validar_cpf', 'O número informado é inválido', function(v){return validaTaxvat(v,0);});
	//]]>
</script>
