<div class="hor-scroll">
    <span class="sub-title">Passo 1</span>
    <table cellspacing="0" class="form-list">
        <tbody>
            <tr>
                <td class="label"><label for="name">Nome <span class="required">*</span></label></td>
                <td class="value">
                    <input type="text" class=" required-entry input-text required-entry" value="" name="name" id="name">            </td>
                <td class="scope-label"><span class="nobr"></span></td>
            </tr>

            <tr>
                <td class="label"><label for="description">Descrição <span class="required">*</span></label></td>
                <td class="value">
                    <textarea cols="15" rows="2" class=" required-entry required-entry textarea" name="description" id="description"></textarea><button style="" onclick="catalogWysiwygEditor.open('http://localhost/comerciodoboi/index.php/admin/catalog_product/wysiwyg/key/4d38247c5d763f1907e212564eeccb60/', 'description')" class="scalable btn-wysiwyg" type="button" title="Editor WYSIWYG" id="id_7c0711e82833174234b80df745e6f92c"><span><span><span>Editor WYSIWYG</span></span></span></button>            </td>
                <td class="scope-label"><span class="nobr"></span></td>
            </tr>

            <tr>
                <td class="label"><label for="sku">Código Identificador (SKU) <span class="required">*</span></label></td>
                <td class="value">
                    <input type="text" class=" required-entry input-text required-entry" value="" name="sku" id="sku">            </td>
                <td class="scope-label"><span class="nobr"></span></td>
            </tr>

            <tr>
                <td class="label"><label for="weight">Peso <span class="required">*</span></label></td>
                <td class="value">
                    <input type="text" class=" required-entry validate-number validate-zero-or-greater validate-number-range number-range-0-99999999.9999 input-text required-entry" value="" name="product[weight]" id="weight">            </td>
                <td class="scope-label"><span class="nobr"></span></td>
            </tr>

            <tr>
                <td class="label"><label for="price">Preço <span class="required">*</span></label></td>
                <td class="value">
                    <input type="text" class=" required-entry validate-zero-or-greater input-text required-entry" value="" name="price" id="price">
                </td>
                <td class="scope-label"><span class="nobr"></span></td>
            </tr>
            <tr>
                <td class="label"><label for="url_img_1">Imagem 1</label></td>
                <td class="value">
                    <input type="file" class="" value="" name="url_img_1" id="url_img_1">            </td>
            </tr>
            <tr>
                <td class="label"><label for="url_img_1">Imagem 1</label></td>
                <td class="value">
                    <input type="file" class="" value="" name="url_img_1" id="url_img_1">            </td>
            </tr>
            <tr>
                <td class="label"><label for="url_img_1">Imagem 1</label></td>
                <td class="value">
                    <input type="file" class="" value="" name="url_img_1" id="url_img_1">            </td>
            </tr>
        </tbody>
    </table>
</div>